# Default values for do500.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Create a helper to create a prefix if one isn't provided? Would help if we moved to shared clusters
prefix: ""

gitlab_app_name: "gitlab-ce"

namespaces:
  - name: do500-workspaces
  - name: do500-gitlab
  - name: do500-slides

operators:
  - name: codeready-workspaces
    namespace: do500-workspaces
    subscription:
      channel: latest
      approval: Automatic
      operatorName: codeready-workspaces
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: crwoperator.v2.0.0
    operatorgroup:
      create: true

gitlab:
  namespace: do500-gitlab
  root_password: Password123
  imagestreams:
    - name: "gitlab-ce"
      tag_name: "gitlab-12.8.7"
      stream_uri: "gitlab/gitlab-ce:12.8.7-ce.0"
    - name: "gitlab-ce-redis"
      tag_name: "5.0.4"
      stream_uri: "redis:5.0.4-alpine"

crw:
  namespace: do500-workspaces
  name: "codeready-workspaces"
  devRegImage: "quay.io/rht-labs/devfileregistry:test"
  tlsSupport: true

docs:
  name: do500-slides
  namespace: do500-slides 
  build:
    source_context_dir: "slides"
    source_repo: "https://github.com/rht-labs/enablement-docs"
    s2i_name: "nodejs"
    s2i_tag: "10"
